name: C++ with CMake CI

on: [push, pull_request]

jobs:
  Bowling Project:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@develop
    - name: mkdir build
      run: mkdir build
    - name: Compile
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: build
      run: ctest -V
